name: Validación de OpenAPI y Fix Changes

# Se ejecuta en eventos de pull request hacia la rama main
on:
  pull_request:
    branches:
      - main
    paths:
      - 'api/contract-bs.yaml'
  push:
    branches:
      - main
    paths:
      - 'api/contract-bs.yaml'    

jobs:
  validate-fix-changes:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Paso 2: Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Paso 3: Instalar swagger-cli globalmente
      - name: Instalar swagger-cli
        run: npm install -g swagger-cli

      # Paso 4: Validar el archivo OpenAPI
      - name: Validar el archivo OpenAPI
        run: swagger-cli validate ./api/contract-bs.yaml

      - name: 'validate openapi schema'
        uses: thiyagu06/openapi-validator-action@v1
        with:
          filepath: './api/contract-bs.yaml'  